import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: '#F2F2F2',
  },
  mainContainer: {
    flex: 1,
    backgroundColor: '#F2F2F2',
    alignItems: 'center',
    marginTop: 41,
    marginTop: 85,
  },
  profileAvatar: {
    width: 70,
    height: 70,
    borderRadius: 50,
  },
  profileNameContainer: {
    width: 125,
    height: 25,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 13.5,
    backgroundColor: '#F8E71C',
    marginTop: -10,
  },
  profileName: {
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 13,
    color: '#4A4A4A',
  },
  memberShip: {
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'normal',
    color: 'rgba(0, 0, 0, 0.65)',
    textAlign: 'center',
    marginTop: 10,
  },
  enterValue: {
    marginBottom: 10,
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'normal',
    color: 'rgba(0, 0, 0, 0.65)',
    textAlign: 'center',
    marginTop: 27,
  },
  purchaseInputContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginLeft: 13,
  },
  dollarImage: {
    width: 12,
    height: 23,
    marginRight: -23,
    zIndex: 999,
  },
  purchaseInput: {
    zIndex: 1,
    width: 130,
    height: 40,
    borderColor: '#D9D9D9',
    borderRadius: 4,
    paddingLeft: 31,
    color: 'rgba(0, 0, 0, 0.85)',
    fontSize: 20,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'normal',
  },
  purchaseContainer: {
    marginTop: 15,
    flex: 1,
    flexDirection: 'row',
  },
  purchaseText: {
    fontSize: 12,
    fontFamily: 'Roboto',
    fontWeight: 'normal',
    fontStyle: 'normal',
    color: 'rgba(0, 0, 0, 0.65)',
  },
  purchaseValue: {
    marginLeft: 4,
    color: '#4076D9',
    fontSize: 12,
    fontFamily: 'Roboto',
    fontWeight: 'normal',
    fontStyle: 'normal',
  },
  grandPointsButtonContainer: {
    marginTop: 95,
    justifyContent: 'center',
    width: 250,
    height: 40,
    borderRadius: 4,
  },
  grandPointsButtonText: {
    textAlign: 'center',
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'normal',
  },
  backButtonContainer: {
    marginTop: 20,
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
    width: 250,
    height: 40,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#4076D9',
  },
  backButtonText: {
    textAlign: 'center',
    color: '#4076D9',
    fontSize: 12,
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: 'bold',
  },
});

export default styles;
