export const images = {
  'bg': require('../img/bg.png'),
  'group-2': require('../img/group-2.png'),
  'group-3': require('../img/group-3.png'),
  'group-4': require('../img/group-4.png'),
  'group-5': require('../img/group-5.png'),
  'group-10': require('../img/group-10.png'),
  '2000px-Louis_Vuitton_Logo': require('../img/2000px-Louis_Vuitton_Logo.svg_.png'),
  'google': require('../img/google.png'),
  'twitter': require('../img/twitter.jpg'),
  'timeless-logos': require('../img/timeless-logos.jpg'),
  'shape-5': require('../img/shape-5.png'),
  'cupon1': require('../img/cupon1.png'),
  'man': require('../img/man.jpg'),
  'strih': require('../img/strih.png'),
  'transactionBackground': require('../img/transactionBackground1.png'),
  'starbucks': require('../img/starbucks.png'),
  'tess': require('../img/tess3.png'),
  'googleIcon': require('../img/googleIcon.png'),
  'sarah': require('../img/sarah.png'),
  'dollar': require('../img/dollar.png'),
  'backarrow': require('../img/backarrow.png'),
  'empty': require('../img/emptyCoupon.png'),
  'edit': require('../img/edit.png'),
  'eye': require('../img/eye.png'),
  'defaultIcon': require('../img/defaultIcon.png'),
  'defaultStore': require('../img/defaultStore.png'),
};
