import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  couponBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
    
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    textAlign: 'center',
    color: 'rgba(0, 0, 0, 0.25)',
    fontSize: 14,
    lineHeight: 16,
    fontWeight: '500',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
  },
  couponContainer: {
    width: '100%',
    height: 160,
    borderWidth: 0,
    shadowRadius: 3.84,
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 2, right: 4 },
  },
  couponSubContainer: {
    flex: 1,
  },
  topContainer: {
    height: 55,
    marginTop: 13,
    marginLeft: 25,
    marginRight: 25,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  topLeftContainer: {
    flex: 1,
    flexDirection: 'column',
  },
  priceContainer: {
    flex: 1,
    width: 240,
    flexDirection: 'row',
  },
  price: {
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '500',
    fontStyle: 'normal',
    fontFamily: 'Roboto',
  },
  estimates: {
    fontSize: 10,
    paddingTop: 7,
    opacity: 0.69,
    paddingLeft: 4,
    color: '#FFFFFF',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontFamily: 'Roboto',
  },
  limitedContainer: {
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  limitedText: {
    fontSize: 12,
    color: '#FFFFFF',
    fontStyle: 'normal',
    fontFamily: 'Roboto',
  },
  profileContainer: {
    flex: 1,
    alignItems: 'flex-end',
    flexDirection: 'column',
  },
  profileIcon: {
    width: 35,
    height: 35,
    marginRight: 2,
    borderRadius: 50,
  },
  profileNameContainer: {
    width: 40,
    height: 15,
    marginTop: -5,
    borderRadius: 8,
    backgroundColor: '#F8E71C',
  },
  profileNameText: {
    fontSize: 8,
    paddingTop: 2,
    fontStyle: 'normal',
    textAlign: 'center',
    fontFamily: 'Roboto',
  },
  bottomContainer: {
    flex: 1,
    marginTop: 15,
    marginLeft: 25,
    marginRight: 25,
    marginBottom: 13,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  bottomLeftContainer: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'flex-end',
  },
  couponCode: {
    fontSize: 12,
    marginLeft: 2,
    marginBottom: 3,
    color: '#FFFFFF',
    fontWeight: '500',
    fontStyle: 'normal',
    fontFamily: 'Roboto',
  },
  couponCodeImage: {
    width: 70,
    height: 30,
    borderRadius: 5,
  },
  bottomRightContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  denyButton: {
    width: 45,
    height: 20,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#FFFFFF',
    justifyContent: 'center',
  },
  denyButtonText: {
    fontSize: 10,
    color: '#FFFFFF',
    fontStyle: 'normal',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontWeight: 'normal',
  },
  approveButton: {
    width: 59,
    height: 20,
    marginLeft: 4,
    borderWidth: 1,
    borderRadius: 4,
    borderColor: '#746DFF',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  approveButtonText: {
    fontSize: 10,
    color: '#4A4A4A',
    textAlign: 'center',
    fontStyle: 'normal',
    fontFamily: 'Roboto',
    fontWeight: 'normal',
  },
});

export default styles;
